### ISSUE TITLE
部分安卓机显示不了

### ISSUE THREAD

**Issue by alphabetaluck** [artwl/Lottery#1]
部分安卓手机刮了没显示，不知道是不是透明没显示，但是百分比回调最后还是执行了

**Comment by alphabetaluck** [comment]
找到解决方案， 找了谷歌N小时也没找到方法，老外遇到了但是没解决，给出核心代码吧，修改drawPoint方法如下就ok了，不是很懂canvas，不知道原因是什么，请知道的解答下
drawPoint: function (x, y) {
        this.maskCtx.beginPath();
        var radgrad = this.maskCtx.createRadialGradient(x, y, 0, x, y, 30);
        radgrad.addColorStop(0, 'rgba(0,0,0,0.6)');
        radgrad.addColorStop(1, 'rgba(255, 255, 255, 0)');
        this.maskCtx.fillStyle = radgrad;
        this.maskCtx.arc(x, y, 20, 20, Math.PI \* 2, true);
        this.maskCtx.fill();
        if (!this.conNode.innerHTML.replace(/[\w\W]| /g, '')) {
            this.conNode.appendChild(this.background);
            this.conNode.appendChild(this.mask);
            this.clientRect = this.conNode ? this.conNode.getBoundingClientRect() : null;
        }
        if (this.drawPercentCallback) {
            this.drawPercentCallback.call(null, this.getTransparentPercent(this.maskCtx, this.width, this.height));
        }
    }

**Comment by artwl** [comment]
这个代码我知道，是https://github.com/manakor/html5-canvas-finger-lottery-ticket-eraser 这个里的。
现在DEMO我测试了中兴U970手机（Android4.0.3系统）：Chrome/Firefox/UC/QQ/百度浏览器 都是OK的

**Comment by alphabetaluck** [comment]
这个是你自己写的drawLottery方法里面的

**Comment by yerz123** [comment]
用'image'的时候会js报错，你们会吗？报错如下
Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data. 
Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data. Lottery.js:27
Lottery.getTransparentPercent Lottery.js:27
Lottery.drawPoint Lottery.js:52
(anonymous function)

**Comment by artwl** [comment]
@yerz123 因为图片跨域了

**Comment by artwl** [comment]
@udbmnm 谢谢指出问题，我在使用过程中也发现了部分android机显示不了的问题，调试后发现是浏览器渲染问题，后来通过弹制重绘解决了。你改的代码又把节点加了一遍，应该不是根本原因。我的代码最开始是fork了 https://github.com/manakor/html5-canvas-finger-lottery-ticket-eraser  这个代码，重构了一下。

**Comment by alphabetaluck** [comment]
@artwl 谢谢分享
